language: node_js
node_js:
- 12
- 14
cache:
  directories:
  - node_modules
sudo: false
before_script:
- npm prune
script:
- npm run lint
- npm run test
- npm run perf
after_script:
- nyc report --reporter=text-lcov | coveralls
- nyc check-coverage --lines 50
- semantic-release
notifications:
  email: false
